### ISSUE TITLE
Unexpected exception thrown when services are not yet up

### ISSUE THREAD

**Issue by natilivni** [sakno/dotNext#54]
Hello,

I am seeing a strange behavior on some of my nodes but not on others.  My first node comes up first and successfully polls for the other members.  The other two members, however, come up, try to connect, get a 403 resonse from the first node and crash with the following error:

```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://0.0.0.0:443
info: CRB.DistributedServices.LockServer.LockServerNodeLifeTime[0]
      Cluster member initialized.
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: QA
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
dbug: DotNext.Net.Cluster.Consensus.Raft.Http.Embedding.RaftEmbeddedCluster[0]
      Sending request of type PreVote to member Unspecified/lockserver01-ingress-svc.lockserver-ns.svc.cluster.local:443
dbug: DotNext.Net.Cluster.Consensus.Raft.Http.Embedding.RaftEmbeddedCluster[0]
      Sending request of type PreVote to member Unspecified/lockserver03-ingress-svc.lockserver-ns.svc.cluster.local:443
warn: DotNext.Net.Cluster.Consensus.Raft.Http.Embedding.RaftEmbeddedCluster[0]
      Cluster member Unspecified/lockserver03-ingress-svc.lockserver-ns.svc.cluster.local:443 is unavailable
System.Net.Http.HttpRequestException: Name or service not known
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at DotNext.Net.Cluster.Consensus.Raft.Http.RaftClusterMember.SendAsync[TResult,TMessage](TMessage message, CancellationToken token) in /_/src/cluster/DotNext.AspNetCore.Cluster/Net/Cluster/Consensus/Raft/Http/RaftClusterMember.cs:line 96
dbug: CRB.DistributedServices.LockServer.LockServerMetricsCollector[0]
      ReportResponseTime: 00:00:00.0433675
dbug: CRB.DistributedServices.LockServer.LockServerMetricsCollector[0]
      ReportResponseTime: 00:00:00.1943564
Unhandled exception. DotNext.Net.Cluster.Consensus.Raft.Http.UnexpectedStatusCodeException: Response status code does not indicate success: 403 (Forbidden).
   at DotNext.Net.Cluster.Consensus.Raft.Http.RaftClusterMember.SendAsync[TResult,TMessage](TMessage message, CancellationToken token) in /_/src/cluster/DotNext.AspNetCore.Cluster/Net/Cluster/Consensus/Raft/Http/RaftClusterMember.cs:line 115
   at DotNext.Net.Cluster.Consensus.Raft.RaftCluster`1.<DotNext.Net.Cluster.Consensus.Raft.IRaftStateMachine.MoveToCandidateState>g__PreVoteAsync|74_0(Int64 currentTerm) in /_/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/RaftCluster.cs:line 740
   at DotNext.Net.Cluster.Consensus.Raft.RaftCluster`1.DotNext.Net.Cluster.Consensus.Raft.IRaftStateMachine.MoveToCandidateState() in /_/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/RaftCluster.cs:line 694
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I am not sure why the first node is returning a 403 (I never configure any authorization) or why such a response would cause a crash of the node.

**Comment by sakno** [comment]
Hi @natilivni ! Do you have `allowedNetworks` in your configuration? 403 response is generated by the library only if requester's IP not in the white list of subnets.

**Comment by natilivni** [comment]
Thank is it. Thank you!

**Comment by sakno** [comment]
In case of Docker or K8S you actually don't need this configuration because these environments provide their own virtual networks which are unavailable externally (only through Ingress).
